CREATE TABLE "VSV58378"."APP_USER_ADDITIONAL_INFO"
(
   APP_ADD_INFO_CD int PRIMARY KEY NOT NULL,
   APP_USER_ROLE_CD int NOT NULL,
   ADDESS_1 char(20) NOT NULL,
   ADDRESS_2 char(20) NOT NULL,
   ADDRESS_3 char(10),
   ZIPCODE char(12) NOT NULL,
   APP_USER_CD int NOT NULL,
   STATUS int NOT NULL,
   IS_PRIMARY int
)

CREATE TABLE "VSV58378"."APP_USER"
(
   APP_USER_CD int PRIMARY KEY NOT NULL,
   FIRSTNAME char(15) NOT NULL,
   LASTNAME char(10),
   MOBILENO char(15) NOT NULL,
   EMAILID char(25) NOT NULL,
   PASSWORD char(40) NOT NULL,
   STATUS int NOT NULL
)
